FROM python:3.14

WORKDIR /src

COPY ./grant_game_consumer/requirements.txt /src/requirements.txt

RUN pip install --no-cache-dir --upgrade pip \
&& pip install --no-cache-dir -r /src/requirements.txt

COPY ./grant_game_consumer /src/grant_game_consumer
COPY .env /src/grant_game_consumer

# installs protos
COPY ./shared/protobufs /src/protobufs
WORKDIR /src/protobufs
RUN rm -rf ./src/*.egg-info ./build .eggs \
    && python -m pip install --no-cache-dir .
WORKDIR /src

CMD ["python", "-m", "grant_game_consumer.main"]
