# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from users_proto import users_service_pb2 as users__proto_dot_users__service__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in users_proto/users_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UserServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.HasGame = channel.unary_unary(
                '/users.v1.UserService/HasGame',
                request_serializer=users__proto_dot_users__service__pb2.HasGameRequest.SerializeToString,
                response_deserializer=users__proto_dot_users__service__pb2.HasGameResponse.FromString,
                _registered_method=True)
        self.AddGameToUser = channel.unary_unary(
                '/users.v1.UserService/AddGameToUser',
                request_serializer=users__proto_dot_users__service__pb2.AddGameToUserRequest.SerializeToString,
                response_deserializer=users__proto_dot_users__service__pb2.AddGameToUserResponse.FromString,
                _registered_method=True)
        self.AddGamesIfNoneOwned = channel.unary_unary(
                '/users.v1.UserService/AddGamesIfNoneOwned',
                request_serializer=users__proto_dot_users__service__pb2.AddGamesIfNoneOwnedRequest.SerializeToString,
                response_deserializer=users__proto_dot_users__service__pb2.AddGamesIfNoneOwnedResponse.FromString,
                _registered_method=True)
        self.GetOwnedGames = channel.unary_unary(
                '/users.v1.UserService/GetOwnedGames',
                request_serializer=users__proto_dot_users__service__pb2.GetOwnedGamesRequest.SerializeToString,
                response_deserializer=users__proto_dot_users__service__pb2.GetOwnedGamesResponse.FromString,
                _registered_method=True)
        self.AddGameToCart = channel.unary_unary(
                '/users.v1.UserService/AddGameToCart',
                request_serializer=users__proto_dot_users__service__pb2.AddGameToCartRequest.SerializeToString,
                response_deserializer=users__proto_dot_users__service__pb2.AddGameToCartResponse.FromString,
                _registered_method=True)
        self.RemoveGameFromCart = channel.unary_unary(
                '/users.v1.UserService/RemoveGameFromCart',
                request_serializer=users__proto_dot_users__service__pb2.RemoveGameFromCartRequest.SerializeToString,
                response_deserializer=users__proto_dot_users__service__pb2.RemoveGameFromCartResponse.FromString,
                _registered_method=True)
        self.GetCart = channel.unary_unary(
                '/users.v1.UserService/GetCart',
                request_serializer=users__proto_dot_users__service__pb2.GetCartRequest.SerializeToString,
                response_deserializer=users__proto_dot_users__service__pb2.GetCartResponse.FromString,
                _registered_method=True)
        self.ClearCart = channel.unary_unary(
                '/users.v1.UserService/ClearCart',
                request_serializer=users__proto_dot_users__service__pb2.ClearCartRequest.SerializeToString,
                response_deserializer=users__proto_dot_users__service__pb2.ClearCartResponse.FromString,
                _registered_method=True)


class UserServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def HasGame(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddGameToUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddGamesIfNoneOwned(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOwnedGames(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddGameToCart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveGameFromCart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearCart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'HasGame': grpc.unary_unary_rpc_method_handler(
                    servicer.HasGame,
                    request_deserializer=users__proto_dot_users__service__pb2.HasGameRequest.FromString,
                    response_serializer=users__proto_dot_users__service__pb2.HasGameResponse.SerializeToString,
            ),
            'AddGameToUser': grpc.unary_unary_rpc_method_handler(
                    servicer.AddGameToUser,
                    request_deserializer=users__proto_dot_users__service__pb2.AddGameToUserRequest.FromString,
                    response_serializer=users__proto_dot_users__service__pb2.AddGameToUserResponse.SerializeToString,
            ),
            'AddGamesIfNoneOwned': grpc.unary_unary_rpc_method_handler(
                    servicer.AddGamesIfNoneOwned,
                    request_deserializer=users__proto_dot_users__service__pb2.AddGamesIfNoneOwnedRequest.FromString,
                    response_serializer=users__proto_dot_users__service__pb2.AddGamesIfNoneOwnedResponse.SerializeToString,
            ),
            'GetOwnedGames': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOwnedGames,
                    request_deserializer=users__proto_dot_users__service__pb2.GetOwnedGamesRequest.FromString,
                    response_serializer=users__proto_dot_users__service__pb2.GetOwnedGamesResponse.SerializeToString,
            ),
            'AddGameToCart': grpc.unary_unary_rpc_method_handler(
                    servicer.AddGameToCart,
                    request_deserializer=users__proto_dot_users__service__pb2.AddGameToCartRequest.FromString,
                    response_serializer=users__proto_dot_users__service__pb2.AddGameToCartResponse.SerializeToString,
            ),
            'RemoveGameFromCart': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveGameFromCart,
                    request_deserializer=users__proto_dot_users__service__pb2.RemoveGameFromCartRequest.FromString,
                    response_serializer=users__proto_dot_users__service__pb2.RemoveGameFromCartResponse.SerializeToString,
            ),
            'GetCart': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCart,
                    request_deserializer=users__proto_dot_users__service__pb2.GetCartRequest.FromString,
                    response_serializer=users__proto_dot_users__service__pb2.GetCartResponse.SerializeToString,
            ),
            'ClearCart': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearCart,
                    request_deserializer=users__proto_dot_users__service__pb2.ClearCartRequest.FromString,
                    response_serializer=users__proto_dot_users__service__pb2.ClearCartResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'users.v1.UserService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('users.v1.UserService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UserService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def HasGame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/users.v1.UserService/HasGame',
            users__proto_dot_users__service__pb2.HasGameRequest.SerializeToString,
            users__proto_dot_users__service__pb2.HasGameResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddGameToUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/users.v1.UserService/AddGameToUser',
            users__proto_dot_users__service__pb2.AddGameToUserRequest.SerializeToString,
            users__proto_dot_users__service__pb2.AddGameToUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddGamesIfNoneOwned(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/users.v1.UserService/AddGamesIfNoneOwned',
            users__proto_dot_users__service__pb2.AddGamesIfNoneOwnedRequest.SerializeToString,
            users__proto_dot_users__service__pb2.AddGamesIfNoneOwnedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOwnedGames(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/users.v1.UserService/GetOwnedGames',
            users__proto_dot_users__service__pb2.GetOwnedGamesRequest.SerializeToString,
            users__proto_dot_users__service__pb2.GetOwnedGamesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddGameToCart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/users.v1.UserService/AddGameToCart',
            users__proto_dot_users__service__pb2.AddGameToCartRequest.SerializeToString,
            users__proto_dot_users__service__pb2.AddGameToCartResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveGameFromCart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/users.v1.UserService/RemoveGameFromCart',
            users__proto_dot_users__service__pb2.RemoveGameFromCartRequest.SerializeToString,
            users__proto_dot_users__service__pb2.RemoveGameFromCartResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/users.v1.UserService/GetCart',
            users__proto_dot_users__service__pb2.GetCartRequest.SerializeToString,
            users__proto_dot_users__service__pb2.GetCartResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClearCart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/users.v1.UserService/ClearCart',
            users__proto_dot_users__service__pb2.ClearCartRequest.SerializeToString,
            users__proto_dot_users__service__pb2.ClearCartResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
